name: "srlua-and-luajit"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - name: Install Dependencies
          run: |
            sudo apt update
            sudo apt install -y libxrandr-dev \
              libgles2-mesa-dev mesa-common-dev libgl1-mesa-dev mesa-vulkan-drivers \
              libfreetype6-dev xorg-dev libxi-dev libx11-dev libasound2-dev \
              nvidia-cg-dev glslang-dev spirv-tools spirv-headers
        - uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Build srlua and luajit for Linux
          run: |
            cd ./LuaJIT-2.1/src
            ./make       
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: Linux luajit
            path: |
              ./bin/linux/luajit
              ./bin/linux/luajit.so

    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - uses: ilammy/msvc-dev-cmd@v1.4.1
        - name: Build srlua and luajit for Win64
          run: |
            cd ./LuaJIT-2.1/src
            ./msvcbuild.bat
          shell: bash
           
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: Windows luajit
            path: |
              ./bin/windows/luajit.exe
              ./bin/windows/lua51.dll
              ./bin/windows/luajit.lib
    build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v4
        - name: Build srlua and luajit for macos
          run: |
            cd ./LuaJIT-2.1/src
            ./make 
              
        - name: Archive results
          uses: actions/upload-artifact@v4
          with:
            name: macOS luajit
            path: |
              ./bin/macos/luajit
              ./bin/linux/luajit.so
    # build-macos-arm64:
    #   runs-on: macos-14
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Build sokol lib for macos arm64
    #       run: ./build-sokol.sh macos_arm64
              
    #     - name: Archive results
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: macOS arm64 sokol
    #         path: |
    #           ./bin/libsokol_dll_macos_arm64.so 
    #           ./bin/libsokol_debug_dll_macos_arm64.so 
    #           ./bin/libsokol_shape_dll_macos_arm64.so
    #           ./bin/libsokol_nuklear_dll_macos_arm64.so
    #           ./bin/libhmm_dll_macos_arm64.so
    #           ./bin/libremotery_dll_macos_arm64.so
    #           ./bin/libstb_dll_macos_arm64.so
    # build-ios64:
    #   runs-on: macos-latest
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Build sokol lib for iosarm64
    #       run: ./build-sokol.sh ios64
              
    #     - name: Archive results
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: ios64 sokol
    #         path: |
    #           ./bin/libsokol_dll_ios64.so 
    #           ./bin/libsokol_debug_dll_ios64.so 
    #           ./bin/libsokol_shape_dll_ios64.so
    #           ./bin/libsokol_nuklear_dll_ios64.so
    #           ./bin/libhmm_dll_ios64.so
    #           ./bin/libremotery_dll_ios64.so
    #           ./bin/libstb_dll_ios64.so
    # build-android:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Fetch NDK
    #       run: wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
    #     - name: Install arm compiler
    #       run: unzip android-ndk-r25b-linux.zip
    #     - name: Rename folder for generic ndk use
    #       run: mv android-ndk-r25b android-ndk
    #     - name: Build sokol lib for android
    #       run: ./build-sokol.sh android
              
    #     - name: Archive results
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: android sokol
    #         path: |
    #           ./bin/sokol_dll_aarch64.so   
    #     - name: Archive armv7 results
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: android sokol
    #         path: |
    #           ./bin/sokol_dll_armv7.so   